apiVersion: v1
kind: Service
metadata:
  name: todo-nodeport
spec:
  selector:
    app: todolist
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30020  # Опціонально (можна не вказувати)
  type: NodePort
